#!/bin/bash

if [ $# -eq 0 ]; then
            echo "Usage: $0 <Target IPv4 address>"
                exit 1
fi

if [[ ! $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Please enter a valid IPv4 address!"
                exit 1
fi


echo "Target IPv4 address: $1"

pod_name=$(kubectl get pods -l app=sccbase -o jsonpath="{.items[0].metadata.name}")

result=$(kubectl exec -ti -c api "$pod_name" -- /usr/bin/sqlite3 /var/lib/rsdbase/db/rsdbase.db "select drawer_id from MODULES where ipv4 == '$1'")
if [ -z "${result}" ]; then
            echo "Not found"
    else
                echo "Drawer ID: $result"
fi
